package View;

import Model.Contas;
import Model.Documento;
import javax.swing.JOptionPane;

/**
 * @author Bruno Giovani Bressanini Cavalheiro
 */
public class Tela extends javax.swing.JFrame {

    private Contas contas = new Contas();
    private Documento documento = new Documento();

    /**
     * Creates new form Tela
     */
    public Tela() {

        initComponents();

        try {

            contas.setExtrato(documento.Carregar());

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e.getMessage());

        }

        lbValorAtualResult.setText(contas.ConsultarSaldo());
        lbValorFuturoResult.setText(contas.ConsultarSaldoTotal());

        areaExtrato.setText(contas.ListarExtrato());
        areaReceita.setText(contas.ListarReceitas());
        areaDespesas.setText(contas.ListarDespesas());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbValorAtual = new javax.swing.JLabel();
        lbValorFuturo = new javax.swing.JLabel();
        lbValorAtualResult = new javax.swing.JLabel();
        lbValorFuturoResult = new javax.swing.JLabel();
        btnReceita = new javax.swing.JButton();
        btnDespesa = new javax.swing.JButton();
        extrato = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaExtrato = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        areaReceita = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        areaDespesas = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Contas");

        lbValorAtual.setText("Valor Atual:");

        lbValorFuturo.setText("Valor Futuro:");

        btnReceita.setText("Receita");
        btnReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceitaActionPerformed(evt);
            }
        });

        btnDespesa.setText("Despesa");
        btnDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDespesaActionPerformed(evt);
            }
        });

        areaExtrato.setEditable(false);
        areaExtrato.setColumns(20);
        areaExtrato.setRows(5);
        jScrollPane3.setViewportView(areaExtrato);

        extrato.addTab("Extrato", jScrollPane3);

        areaReceita.setEditable(false);
        areaReceita.setColumns(20);
        areaReceita.setRows(5);
        jScrollPane5.setViewportView(areaReceita);

        extrato.addTab("Receita", jScrollPane5);

        areaDespesas.setEditable(false);
        areaDespesas.setColumns(20);
        areaDespesas.setRows(5);
        jScrollPane6.setViewportView(areaDespesas);

        extrato.addTab("Despesas", jScrollPane6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(extrato, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbValorAtual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbValorAtualResult))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbValorFuturo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbValorFuturoResult)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReceita, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDespesa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbValorAtual)
                    .addComponent(lbValorAtualResult)
                    .addComponent(btnReceita))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbValorFuturo)
                    .addComponent(lbValorFuturoResult)
                    .addComponent(btnDespesa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(extrato, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDespesaActionPerformed

        telaDespesa telaModal = new telaDespesa(this, true, contas);
        telaModal.setVisible(true);

        lbValorAtualResult.setText(contas.ConsultarSaldo());
        lbValorFuturoResult.setText(contas.ConsultarSaldoTotal());

        areaExtrato.setText(contas.ListarExtrato());
        areaDespesas.setText(contas.ListarDespesas());

        JOptionPane.showMessageDialog(null, "Despesa registrada com sucesso.");

    }//GEN-LAST:event_btnDespesaActionPerformed

    private void btnReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceitaActionPerformed

        telaReceita telaModal = new telaReceita(this, true, contas);
        telaModal.setVisible(true);

        lbValorAtualResult.setText(contas.ConsultarSaldo());
        lbValorFuturoResult.setText(contas.ConsultarSaldoTotal());

        areaExtrato.setText(contas.ListarExtrato());
        areaReceita.setText(contas.ListarReceitas());

        JOptionPane.showMessageDialog(null, "Receita registrada com sucesso.");

    }//GEN-LAST:event_btnReceitaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaDespesas;
    private javax.swing.JTextArea areaExtrato;
    private javax.swing.JTextArea areaReceita;
    private javax.swing.JButton btnDespesa;
    private javax.swing.JButton btnReceita;
    private javax.swing.JTabbedPane extrato;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lbValorAtual;
    private javax.swing.JLabel lbValorAtualResult;
    private javax.swing.JLabel lbValorFuturo;
    private javax.swing.JLabel lbValorFuturoResult;
    // End of variables declaration//GEN-END:variables
}
